[package]
name = "group_anagrams"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]

[dev-dependencies]
proptest.workspace = true