[package]
name = "string_encode_and_decode"
edition = "2024"
authors.workspace = true
description.workspace = true
license.workspace = true
version.workspace = true

[dependencies]

[dev-dependencies]
proptest.workspace = true